name: Generate Documentation Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - main  # Trigger when PRs are merged into main

  workflow_dispatch:  # ✅ Allows manual triggering from GitHub UI

jobs:
  generate-changelog:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vectara-docs Repository
        uses: actions/checkout@v3

      - name: Clone product-management-tools Repository
        uses: actions/checkout@v3
        with:
          repository: vectara/product-management-tools
          token: ${{ secrets.DOC_CHANGELOG_TOKEN }}
          path: product-management-tools

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install dependencies directly

      - name: Generate Changelog
        env:
          DOC_CHANGELOG_TOKEN: ${{ secrets.DOC_CHANGELOG_TOKEN }}
        run: |
          python product-management-tools/doc-changelog/doc-changelog.py  # Corrected path

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add DocCHANGELOG.md
          git commit -m "📖 Auto-update DocCHANGELOG.md [skip ci]" || echo "No changes to commit"
          git push
